# Generated by Django 4.2.2 on 2023-07-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_education_file_alter_education_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
    ]
