# Generated by Django 4.2.2 on 2023-06-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'Ingilizce'), ('tr', 'Turkce')], default='en', max_length=2)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('sender', models.CharField(max_length=128)),
                ('subtitle', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='static/assets/images/all/')),
                ('file', models.FileField(upload_to='static/assets/images/all/')),
                ('author', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=128)),
                ('pages', models.IntegerField()),
                ('dill', models.CharField(max_length=64)),
                ('bookcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.bookcategory')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
